import json
import re
from datetime import date, datetime
from decimal import Decimal
from typing import Any


# ==============================================================
# CONSTANTS
# ==============================================================


VALID_ASSESSMENTS = {
    "SUPPORTS",
    "PARTIALLY_SUPPORTS",
    "NEUTRAL",
    "PARTIALLY_CONTRADICTS",
    "CONTRADICTS",
    "INSUFFICIENT_DATA",
}


ALLOWED_PERIOD_NUMBERS = {
    1,
    7,
    10,
    14,
    20,
    30,
    50,
    52,
    90,
    365,
}


DATE_PATTERN = re.compile(
    r"\b\d{4}-\d{2}-\d{2}\b"
)


# Supports:
#
# 315.34
# -0.89
# 1,470
# 65.64 M
# 65.64M
# 4.62 B
# 1.2T
#
# Negative lookbehind prevents extracting indicator periods from
# strings such as RSI14 or SMA20.
NUMBER_PATTERN = re.compile(
    r"(?<![\w])"
    r"[-+]?"
    r"(?:\d{1,3}(?:,\d{3})+|\d+)"
    r"(?:\.\d+)?"
    r"(?:\s*[KkMmBbTt](?![A-Za-z]))?"
)


UNIT_MULTIPLIERS = {
    "k": 1_000.0,
    "m": 1_000_000.0,
    "b": 1_000_000_000.0,
    "t": 1_000_000_000_000.0,
}


NEGATIVE_DIRECTION_WORDS = {
    "down",
    "below",
    "decline",
    "declined",
    "declining",
    "decrease",
    "decreased",
    "decreasing",
    "drop",
    "dropped",
    "fall",
    "fell",
    "fallen",
    "lower",
    "negative",
    "loss",
    "lost",
    "under",
}


POSITIVE_DIRECTION_WORDS = {
    "up",
    "above",
    "increase",
    "increased",
    "increasing",
    "gain",
    "gained",
    "higher",
    "positive",
    "rise",
    "rose",
    "rising",
}


# ==============================================================
# TEXT NORMALIZATION
# ==============================================================


def _normalize_text(
    text: str,
) -> str:
    """
    Normalizes Unicode characters commonly generated by LLMs.
    """

    replacements = {
        # Unicode dash/minus variants.
        "\u2010": "-",
        "\u2011": "-",
        "\u2012": "-",
        "\u2013": "-",
        "\u2014": "-",
        "\u2212": "-",
        "\ufe63": "-",
        "\uff0d": "-",

        # Unicode spaces commonly used between a number and unit.
        "\u00a0": " ",
        "\u202f": " ",
        "\u2007": " ",
    }

    for source, target in replacements.items():
        text = text.replace(
            source,
            target,
        )

    return text


# ==============================================================
# SOURCE VALUE EXTRACTION
# ==============================================================


def _collect_context_values(
    value: Any,
    numbers: list[float],
    dates: set[str],
):
    """
    Recursively extracts numerical values and dates from
    Research Context.
    """

    if value is None:
        return

    if isinstance(value, bool):
        return

    if isinstance(value, datetime):
        dates.add(
            value.date().isoformat()
        )
        return

    if isinstance(value, date):
        dates.add(
            value.isoformat()
        )
        return

    if isinstance(
        value,
        (int, float, Decimal),
    ):
        numbers.append(
            float(value)
        )
        return

    if isinstance(value, dict):

        for nested_value in value.values():

            _collect_context_values(
                nested_value,
                numbers,
                dates,
            )

        return

    if isinstance(
        value,
        (list, tuple),
    ):
        # Length may itself be a valid fact.
        numbers.append(
            float(len(value))
        )

        for nested_value in value:

            _collect_context_values(
                nested_value,
                numbers,
                dates,
            )

        return

    if isinstance(value, str):

        normalized = _normalize_text(
            value.strip()
        )

        for found_date in DATE_PATTERN.findall(
            normalized
        ):

            dates.add(
                found_date
            )


# ==============================================================
# NUMERIC CLAIM EXTRACTION
# ==============================================================


def _extract_report_numeric_claims(
    report: dict[str, Any],
) -> list[dict[str, Any]]:
    """
    Extracts numerical claims from an LLM report.

    Supported examples:

        315.34
        -0.89
        1,470
        65.64 M
        47.69M
        4.62 B
        1.2T

    Compact financial units are normalized before source
    comparison:

        65.64 M -> 65,640,000

    Both the displayed number and normalized number are preserved.
    """

    text = json.dumps(
        report,
        ensure_ascii=False,
    )

    text = _normalize_text(
        text
    )

    # Remove complete dates before numerical extraction so that:
    #
    # 2026-09-09
    #
    # is not interpreted as three separate financial numbers.
    text_without_dates = DATE_PATTERN.sub(
        "",
        text,
    )

    claims: list[dict[str, Any]] = []

    for match in NUMBER_PATTERN.finditer(
        text_without_dates
    ):

        raw_value = (
            match
            .group()
            .strip()
        )

        # Remove ordinary / Unicode spaces normalized above.
        compact_value = re.sub(
            r"\s+",
            "",
            raw_value,
        )

        unit = None

        if (
            compact_value
            and compact_value[-1].lower()
            in UNIT_MULTIPLIERS
        ):
            unit = (
                compact_value[-1]
                .lower()
            )

            numeric_part = (
                compact_value[:-1]
            )

        else:
            numeric_part = (
                compact_value
            )

        # Thousands separators are presentation syntax,
        # not decimal syntax.
        #
        # "1,470" -> "1470"
        numeric_part = (
            numeric_part.replace(
                ",",
                "",
            )
        )

        try:
            display_value = float(
                numeric_part
            )

        except ValueError:
            continue

        # Common time-window and indicator numbers such as:
        #
        # RSI14
        # SMA20
        # SMA50
        # 30-day
        # 52-week
        #
        # A number with a compact unit must NOT be ignored:
        #
        # 20M means 20 million, not a 20-day period.
        if (
            unit is None
            and display_value.is_integer()
            and abs(int(display_value))
            in ALLOWED_PERIOD_NUMBERS
        ):
            continue

        multiplier = (
            UNIT_MULTIPLIERS.get(
                unit,
                1.0,
            )
        )

        normalized_value = (
            display_value
            * multiplier
        )

        # Capture nearby text because direction may be expressed
        # semantically rather than through a minus sign.
        #
        # Example:
        #
        # "0.89% below..."
        #
        # may represent source value -0.8915.
        context_start = max(
            0,
            match.start() - 45,
        )

        context_end = min(
            len(text_without_dates),
            match.end() + 45,
        )

        surrounding_text = (
            text_without_dates[
                context_start:context_end
            ]
            .lower()
        )

        claims.append(
            {
                # Number exactly as displayed, without unit.
                "value": display_value,

                # Number transformed to its actual scale.
                #
                # 65.64M -> 65,640,000
                "normalized_value": (
                    normalized_value
                ),

                "raw": raw_value,

                # k / m / b / t or None.
                "unit": unit,

                "context": surrounding_text,
            }
        )

    return claims


# ==============================================================
# DIRECTION DETECTION
# ==============================================================


def _contains_direction_word(
    text: str,
    words: set[str],
) -> bool:
    """
    Detects complete direction words in nearby text.
    """

    tokens = re.findall(
        r"[a-zA-Z]+",
        text.lower(),
    )

    return any(
        token in words
        for token in tokens
    )


def _claim_has_negative_direction(
    claim: dict[str, Any],
) -> bool:
    """
    Returns True when the claim explicitly or semantically
    represents a negative direction.
    """

    value = claim["value"]

    if value < 0:
        return True

    return _contains_direction_word(
        claim["context"],
        NEGATIVE_DIRECTION_WORDS,
    )


def _claim_has_positive_direction(
    claim: dict[str, Any],
) -> bool:
    """
    Returns True when the claim explicitly or semantically
    represents a positive direction.
    """

    value = claim["value"]

    if (
        value > 0
        and not _claim_has_negative_direction(
            claim
        )
    ):
        return True

    return _contains_direction_word(
        claim["context"],
        POSITIVE_DIRECTION_WORDS,
    )


# ==============================================================
# ROUNDING
# ==============================================================


def _values_match_with_rounding(
    report_value: float,
    source_value: float,
) -> bool:
    """
    Checks exact equality and legitimate presentation rounding.

    This function intentionally remains reasonably strict.

    It accepts normal presentation differences such as:

        source = -0.8915
        report = -0.89

    but does not allow arbitrary unrelated numerical values.
    """

    if report_value == source_value:
        return True

    report_is_integer = (
        float(report_value).is_integer()
    )

    source_is_integer = (
        float(source_value).is_integer()
    )

    # If both values are integer counts they must be exact.
    #
    # This prevents:
    #
    # source = 1470
    # report = 1471
    #
    # from passing through a percentage-based tolerance.
    if (
        report_is_integer
        and source_is_integer
    ):
        return False

    # Legitimate presentation rounding to an integer.
    #
    # Example:
    #
    # 57.14 -> 57
    if report_is_integer:

        if abs(
            report_value
            - source_value
        ) <= 0.5:

            return True

    # Small tolerance for floating-point representation and
    # normal display rounding.
    tolerance = max(
        0.02,
        abs(source_value) * 0.005,
    )

    if abs(
        report_value
        - source_value
    ) <= tolerance:

        return True

    # Explicit common presentation rounding.
    if report_value == round(
        source_value,
        1,
    ):
        return True

    if report_value == round(
        source_value,
        2,
    ):
        return True

    if report_value == round(
        source_value,
        3,
    ):
        return True

    if report_value == round(
        source_value,
        4,
    ):
        return True

    return False


# ==============================================================
# COMPACT-UNIT MATCHING
# ==============================================================


def _compact_unit_matches_source(
    claim: dict[str, Any],
    source_value: float,
) -> bool:
    """
    Checks a source number against a value written with a compact
    financial unit.

    Example:

        source:
            65,637,842

        report:
            65.64 M

    The source is first converted into millions:

        65.637842

    and then compared with the displayed value 65.64 using the
    same presentation-rounding rules.

    This is safer than comparing only:

        65,640,000 vs 65,637,842

    because the report intentionally loses precision when it uses
    compact notation.
    """

    unit = claim.get(
        "unit"
    )

    if not unit:
        return False

    multiplier = (
        UNIT_MULTIPLIERS.get(
            unit
        )
    )

    if multiplier is None:
        return False

    source_display_value = (
        source_value
        / multiplier
    )

    return _values_match_with_rounding(
        claim["value"],
        source_display_value,
    )


# ==============================================================
# NUMERICAL GROUNDING
# ==============================================================


def _claim_matches_source(
    claim: dict[str, Any],
    source_values: list[float],
) -> bool:
    """
    Checks whether a numerical claim can be traced to Research
    Context.

    Supported cases include:

    1. Direct value:

        source = 315.34
        report = 315.34

    2. Ordinary rounding:

        source = -0.8915
        report = -0.89

    3. Thousands formatting:

        source = 1470
        report = 1,470

    4. Compact financial notation:

        source = 65,637,842
        report = 65.64 M

    5. Negative source written as positive magnitude where nearby
       wording carries the negative direction:

        source = -6.8307
        report = "6.83% below the 52-week high"
    """

    report_value = claim.get(
        "normalized_value",
        claim["value"],
    )

    # ----------------------------------------------------------
    # 1. NORMAL SIGN-PRESERVING MATCH
    # ----------------------------------------------------------

    for source_value in source_values:

        # Ordinary/direct value comparison.
        if _values_match_with_rounding(
            report_value,
            source_value,
        ):
            return True

        # Compact-unit presentation comparison.
        #
        # Example:
        #
        # source = 65,637,842
        # report = 65.64 M
        if _compact_unit_matches_source(
            claim,
            source_value,
        ):
            return True

    # ----------------------------------------------------------
    # 2. NEGATIVE SOURCE EXPRESSED AS POSITIVE MAGNITUDE
    # ----------------------------------------------------------

    # Example:
    #
    # source = -6.8307
    #
    # report text:
    # "6.83% below its 52-week high"
    #
    # The report contains +6.83 numerically, but the word
    # "below" carries the negative semantic direction.
    if (
        report_value >= 0
        and _claim_has_negative_direction(
            claim
        )
    ):

        for source_value in source_values:

            if source_value >= 0:
                continue

            if _values_match_with_rounding(
                abs(report_value),
                abs(source_value),
            ):
                return True

            # Same semantic-direction logic for compact units.
            unit = claim.get(
                "unit"
            )

            if unit:

                multiplier = (
                    UNIT_MULTIPLIERS.get(
                        unit
                    )
                )

                if multiplier:

                    source_display_value = (
                        abs(source_value)
                        / multiplier
                    )

                    if _values_match_with_rounding(
                        abs(claim["value"]),
                        source_display_value,
                    ):
                        return True

    return False


# ==============================================================
# REPORT DATE EXTRACTION
# ==============================================================


def _extract_report_dates(
    report: dict[str, Any],
) -> set[str]:
    """
    Extracts ISO-formatted dates from the generated report.
    """

    text = json.dumps(
        report,
        ensure_ascii=False,
    )

    text = _normalize_text(
        text
    )

    return set(
        DATE_PATTERN.findall(
            text
        )
    )


# ==============================================================
# MAIN VALIDATION
# ==============================================================


def validate_report_against_context(
    report: dict[str, Any],
    context: dict[str, Any],
) -> dict[str, Any]:
    """
    Performs deterministic grounding validation before
    persistence to Lakebase.

    A generated report must pass all deterministic checks before
    it can be persisted.
    """

    errors: list[str] = []
    warnings: list[str] = []

    # ==========================================================
    # 1. SOURCE FACTS
    # ==========================================================

    source_numbers: list[float] = []
    source_dates: set[str] = set()

    _collect_context_values(
        context,
        source_numbers,
        source_dates,
    )

    # ==========================================================
    # 2. TICKER
    # ==========================================================

    expected_ticker = (
        str(
            context
            .get("watchlist", {})
            .get("ticker", "")
        )
        .strip()
        .upper()
    )

    report_ticker = (
        str(
            report.get(
                "ticker",
                "",
            )
        )
        .strip()
        .upper()
    )

    if report_ticker != expected_ticker:

        errors.append(
            "Ticker mismatch: "
            f"context={expected_ticker}, "
            f"report={report_ticker}"
        )

    # ==========================================================
    # 3. THESIS ASSESSMENT
    # ==========================================================

    assessment = (
        report
        .get(
            "thesis_alignment",
            {},
        )
        .get("assessment")
    )

    if assessment not in VALID_ASSESSMENTS:

        errors.append(
            "Invalid thesis assessment: "
            f"{assessment}"
        )

    # ==========================================================
    # 4. DATES
    # ==========================================================

    report_dates = (
        _extract_report_dates(
            report
        )
    )

    unsupported_dates = sorted(
        report_dates
        - source_dates
    )

    if unsupported_dates:

        errors.append(
            "Report contains date(s) not found "
            "in Research Context: "
            + ", ".join(
                unsupported_dates
            )
        )

    # ==========================================================
    # 5. NUMERIC CLAIMS
    # ==========================================================

    report_claims = (
        _extract_report_numeric_claims(
            report
        )
    )

    unsupported_claims = []

    for claim in report_claims:

        if not _claim_matches_source(
            claim,
            source_numbers,
        ):

            unsupported_claims.append(
                claim
            )

    # ----------------------------------------------------------
    # Remove duplicate unsupported claims while preserving
    # useful diagnostic context.
    # ----------------------------------------------------------

    unique_unsupported: dict[
        tuple[float, str | None],
        dict[str, Any],
    ] = {}

    for claim in unsupported_claims:

        # Include the unit in the key so that:
        #
        # 65.64
        # 65.64 M
        #
        # remain distinguishable during diagnostics.
        key = (
            claim["value"],
            claim.get("unit"),
        )

        if key not in unique_unsupported:
            unique_unsupported[key] = claim

    if unique_unsupported:

        values = ", ".join(
            claim["raw"]
            for claim
            in unique_unsupported.values()
        )

        errors.append(
            "Report contains numerical value(s) "
            "that cannot be traced to Research Context: "
            + values
        )

        # Diagnostic warning with nearby language.
        for claim in unique_unsupported.values():

            snippet = (
                claim["context"]
                .replace(
                    "\n",
                    " ",
                )
                .strip()
            )

            warnings.append(
                "Unsupported numerical claim "
                f"{claim['raw']} near: "
                f"...{snippet}..."
            )

    # ==========================================================
    # 6. DISCLAIMER
    # ==========================================================

    expected_disclaimer = (
        "Research information only. "
        "Not investment advice."
    )

    if (
        report.get("disclaimer")
        != expected_disclaimer
    ):

        errors.append(
            "Research disclaimer is missing "
            "or has been modified."
        )

    # ==========================================================
    # 7. DATA-AS-OF
    # ==========================================================

    report_data_as_of = (
        report.get(
            "data_as_of"
        )
    )

    if report_data_as_of:

        report_data_as_of = (
            _normalize_text(
                str(
                    report_data_as_of
                )
            )
        )

        if (
            source_dates
            and report_data_as_of
            not in source_dates
        ):

            errors.append(
                "data_as_of is not present "
                "among source dates: "
                f"{report_data_as_of}"
            )

    # ==========================================================
    # 8. RESULT
    # ==========================================================

    status = (
        "PASS"
        if not errors
        else "FAIL"
    )

    return {
        "status": status,

        "errors": errors,

        "warnings": warnings,

        "checked_report_numbers": len(
            report_claims
        ),

        "source_numeric_values": len(
            source_numbers
        ),

        "checked_report_dates": len(
            report_dates
        ),

        "source_dates": sorted(
            source_dates
        ),
    }